apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multi-domain-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod  # ใช้ Let's Encrypt ออกใบรับรอง SSL
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - play.domain.com
    - backoffice.domain.com
    - api.domain.com
    secretName: multi-domain-tls
  rules:
  - host: play.domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
  - host: backoffice.domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backoffice-service
            port:
              number: 80
  - host: api.domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-service
            port:
              number: 80
