apiVersion: v1
kind: Service
metadata:
  name: play-service
spec:
  selector:
    app: play
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP  # เปลี่ยนจาก NodePort เป็น ClusterIP